apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-reverse-ip
  template:
    metadata:
      labels:
        app: flask-reverse-ip
    spec:
      containers:
      - name: flask-reverse-ip
        image: kishore363/flask-reverse-ip:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://username:password@app-postgresql:5432/database"
